### ISSUE TITLE
unclear maildrop statement `}` in documentation

### ISSUE THREAD

**Issue by bebehei** [svarshavchik/courier-libs#2]
Hi,
#### status quo

maildrop tells me in the documentation
- that I have to separate different statements eiter by linebreak or `;`

```
#This works:
DESTDIR="mailbox"
to $DESTDIR
#This works:
DESTDIR="mailbox"; to $DESTDIR
# This does not work (obviously)
DESTDIR="mailbox" to $DESTDIR
```
- to use if/else/elsif in the C-style way

```
# this works
if(COND)
{
   do..
}
# So it does not work:
if(COND) {
   do..
}
# neither this:
if(COND) { do.. }
```

But the documentation is quite unclear about the type of `{` and `}`. As I experienced, these are statements, too. So they could be written in one line to with `;`:

```
# Works:
if(COND); {; do.. ; }
```

Could you clearify this in the documentation of maildropfilter?

**Comment by svarshavchik** [comment]
The existing documentation in maildropfilter goes into some detail explaining the syntax of `if`. Feel free to suggest specific changes to "if"'s documentation.
