### ISSUE TITLE
Stressing imap server

### ISSUE THREAD

**Issue by chloe-alverti** [svarshavchik/courier-libs#21]
Hi!

I would like to kindly ask if you have a 
tool to recommend for stressing imap performance
and especially the fetch command. 

I am trying to experiment with imap and Intel Optane nvdimm storage technology. 
In that direction, I am trying to figure out if using mmio vs read
to fetch mail content improves performance.

Also I would like to kindly ask, if courier uses a new process (fork) per connection.

Best Regards,
Chloe

**Comment by svarshavchik** [comment]
I don't have any tools that I recommend, unfortunately. You can try asking this on the courier-users mailing list.

And yes, courier forks a process per connection. Additionally, if the connection uses TLS a second process gets forked, per connection, to handle the encryption and decryption.
