### ISSUE TITLE
mkcategories.pl and mkscripts.pl missing from courier-unicode-2.2.3.tar.bz2

### ISSUE THREAD

**Issue by roelvanmeer** [svarshavchik/courier-libs#23]
Hi Sam,

It seems that the mkcategories.pl and mkscripts.pl files are missing from the courier-unicode-2.2.3.tar.bz2 tarball. I'm trying to update the Debian package from 2.1.2 to 2.2.3 and these files are needed to build 2.2.3. Could you perhaps remedy that in the next release?

I couldn't find any tooling that you might use to make these tarballs, so I can't make a pull request unfortunately.

Best regards, Roel

**Comment by svarshavchik** [comment]
The scripts are in the git repo and are using to robo-generate the C/C++ code that's packaged in the tarball. They should not be needed when building from the tarball. mkscripts.pl gets used to generate scriptstab.h and mkcategories.pl gets used to generate categoriestab.h, which are included in the tarball.

What is the reason those scripts need to be packaged?

**Comment by roelvanmeer** [comment]
It's the Debian packaging: they have a patch [1] which ensures courier-unicode is built against the system unicode data, which I'm trying to update for 2.2.3. It might be that the unicode data is newer than scriptstab.h and categoriestab.h, causing the makefile to want to rebuild those files. Many of the other mk*.pl files are in fact present in the tarball, only these two are missing, which is why I thought this was an omission.

[1] https://salsa.debian.org/debian/courier-unicode/-/blob/master/debian/patches/0001-Use-data-files-from-unicode-data-and-w3c-dtd-xhtml-p.patch

**Comment by svarshavchik** [comment]
I verified that these scripts are in git, so they're just not packaged in the tarball. It's possible that others are, even though they're not used during building. I should remove them, if they're not being used when building from the tarball than they're not needed.

As far as the unicode source data, it's more than just UnicodeData.txt that gets compiled in. Unless all of the source Unicode data is available then it's probably not a good idea to rebuild things partially.

**Comment by roelvanmeer** [comment]
It would be most helpful if you would add these two to the tarball. Removing the others would at least remove the small inconsistency, but it would make life much harder for the Debian devs, so I would kindly ask you to just add these two instead.

Thanks for all your work by the way, I'm a long time happy user of cone, in the process of building the latest version on Debian, which led me down this courier-unicode path.

**Comment by svarshavchik** [comment]
Ok, I added them to the tarball.
