### ISSUE TITLE
Installation instructions missing

### ISSUE THREAD

**Issue by anthonygreen** [svarshavchik/courier-libs#3]
The SourceForge version of the Courier Unicode Library has `configure`, `Makefile` and `INSTALL` files.
`configure`, `Makefile` have been added to `.gitignore` excluding and `INSTALL` is missing. It's unclear how to compile the library now.

**Comment by svarshavchik** [comment]
The installation instructions are on the web site, http://www.courier-mta.org/unicode/INSTALL.html

Only the autotool sources (configure.ac, Makefile.am) are in the repository. autogenereated autotools code is not.
