### ISSUE TITLE
lstat calls on glusterfs causes slowdowns

### ISSUE THREAD

**Issue by jkroonza** [svarshavchik/courier-libs#31]
Hi,

Not an issue on "local" filesystems and currently under control on glusterfs, but I suspect it's going to be the next bottleneck. (stat on glusterfs is notoriously slow)

Didn't strace on a POP3 case yet, but for IMAP when opening a folder a sequence of readdir()s is done, sometimes followed by a sequence of fstatat calls jammed between open and close.  The apparent location for this sequence of calls are maildir/maildiropen.c, and the purpose apparently is to determine if there are unsafe symlinks in the maildir, called from somewhere I'm unable to determine, but strace shows the sequence fd = openat(filename) fcntl(fd) fstatat(fd, AT_EMPTY_PATH) fstatat(FD_CURFD, filename) close(fd) - which can only mean a sequence of calls to maildir_safeopen_stat() directly followed by close, I cannot find this in the code so if you have any idea of where this may come from some pointer would not go amis (ie, is this sequence of calls even required).  I also cannot reproduce arbitrarily, but we see this on fresh syncs using office365/outlook on large mailboxes which takes several minutes before starting to download email (connects using TLS so also can't tcpdump for the exact command to which triggers this).

In the case where we can guarantee that nothing other than courier-imap and exim puts files into these folders, I don't see any possible way to inject symbolic links into the filesystem here.

Would it be safe otherwise to add a configuration option like NO_SYMLINK_CHECK which if it's set will simply return fd prior to the stat calls (the fctnl and fstat calls will need to be split into separate if statements), unless stat1 is non-NULL in which case at least the one stat will need to be performed anyway (maildir_safeopen gets updated to pass stat1 as NULL).

What would be the risks associated with this?

**Comment by svarshavchik** [comment]
This is a defensive measure designed to prevent privilege escalation to leverage a partially-compromised system in order to exfiltrate additional information or compromise it further. I.e., a partial access to the filesystem containing mailboxes, then installing a symlink to /etc/passwd in the maildir, and then using imap to read it.

Having said that I wouldn't object to adding a configuration option to stub it out.

**Comment by jkroonza** [comment]
Thanks.  Security always seems to be a measure of performance/usability vs security.  And I hate that it is what it is.  In our case I'm 99% certain that if we're compromised to the level where an attacker can place a symlink here we've got MUCH BIGGER problems.

Thanks for the feedback, appreciated.  You wouldn't happen to know what would cause the open/close loop (without reading from the file at all)?

**Comment by svarshavchik** [comment]
I suspect it's sub-optimal logic in the IMAP client that does not cache IMAP message data, and instead does something like FETCH 1:* (....).

SELECTing a folder is heavily optimized, and amounts to a readdir, and some other work, avoiding the need to stat each file in the maildir as much as possible.

To work a FETCH 1:* the imap server will end up looping over each message. I suspect that one of the items that the IMAP client requests would be INTERNALDATE, which requires opening and stat-ing the opened file.

**Comment by jkroonza** [comment]
INTERNALDATE can be deduced from the filename though can it not?  Or does INTERNALDATE refer to something other than the delivery date (which is the timestamp in the filename)?

I'm assuming it will only read() from the file if it needs actual headers?  So the information required is either calculated from the stat information, or the filename itself by implication, if you can point me I can look at if I can avoid the open call unless it's actually needed (ie, legit need for stat, or for read).
