### ISSUE TITLE
Missing license information?

### ISSUE THREAD

**Issue by comburent** [svarshavchik/courier-libs#35]
e.g. https://github.com/svarshavchik/courier-libs/blob/master/threadlib/pthread.c mentions a `COPYING` file but I don't see it anywhere?

P.S.: consider using something like [REUSE](https://reuse.software/tutorial/) to convey licensing information in an unambiguous manner instead of a plain COPYING file.

**Comment by svarshavchik** [comment]
Courier's actually packaging combines the courier-libs repository with courier, depending on the project, and the main project supplies the COPYING file.

**Comment by comburent** [comment]
> Courier's actual source packaging combines the courier-libs repository with courier, depending on the project, and the main project supplies the COPYING file.

Which one is the main project?
The reply on <https://github.com/svarshavchik/courier/issues/53> is leaving me confused since I don't see this `COPYING` file in either repositories.

**Comment by svarshavchik** [comment]
All of them are "main", and rule the roost. See "INSTALLME" in the courier repository.

**Comment by comburent** [comment]
> All of them are "main", and rule the roost. See "INSTALLME" in the courier repository.

Hmm… OK, but I still can't find this `COPYING` file, can you give me a link pointing to it?

**Comment by svarshavchik** [comment]
https://github.com/svarshavchik/courier/blob/master/courier/COPYING is a symlink to libs/common/COPYING

After running INSTALLME, this will resolve to

https://github.com/svarshavchik/courier-libs/blob/master/common/COPYING

**Comment by comburent** [comment]
> https://github.com/svarshavchik/courier-libs/blob/master/common/COPYING

Thanks.
Another question, is this _GPL-3.0-only_ or is it _GPL-3.0-or-later_?

**Comment by svarshavchik** [comment]
GPL-3.0-only

**Comment by svarshavchik** [comment]
It goes without saying that the FSF would like to have the ability to update the GPL unilaterally and have it automatically take effect for as many projects as possible.

I prefer to make that decision by myself.

**Comment by comburent** [comment]
> It goes without saying that the FSF would like to have the ability to update the GPL unilaterally and have it automatically take effect for as many projects as possible.
> 
> I prefer to make that decision by myself.

Right, thanks for clarifying.
