### ISSUE TITLE
DST problem in rfc822_mkdate_buf

### ISSUE THREAD

**Issue by andrewmccarthy** [svarshavchik/courier-libs#37]
If I'm reading it correctly, `rfc822_mkdate_buf` in [rfc822/rfc822_mkdate.c](https://github.com/svarshavchik/courier-libs/blob/3f67c3f17c4dbd90081bf5656f9bc5cc1e19daec/rfc822/rfc822_mkdate.c#L68) always adds an hour when the `tm_isdst` flag is set. In Ireland, unusually, the standard time is summer time with the winter time the "different" one. The Europe/Dublin timezone data therefore has the DST flag set in the winter, and the time is -1 hour from the usual.

By always adding an hour the error is compounded and the timezone is reported as +0200 instead of +0000, which is a particularly noticeable problem with Apple Mail which displays the INTERNALDATE by default (whereas most use the Date: header).

Thanks!

**Comment by svarshavchik** [comment]
This is just one of three conditionally-compiled ways of determining the local timezone offset.

It should be sufficient to reorder the configure script to check for tm_gmtoff or altzone availability. This change was committed.
