### ISSUE TITLE
Split libraries up

### ISSUE THREAD

**Issue by anthonygreen** [svarshavchik/courier-libs#4]
I'd like to add the unicode library as a Homebrew formula. 
It would ease integration if the libraries where separate projects, perhaps under a project organisation a la Homebrew. 
The releases(.zip, .tar.gz) are also bundled up together as with other libraries in the repository rather than discreet individual libraries, this is confusing.

**Comment by svarshavchik** [comment]
Given the number of libraries, and their dependencies, were they split up into separate repos the build process would be too cumbersome. There's a long, 20-year history behind the project that resulted in the libraries' organization evolved to their current form.
