### ISSUE TITLE
reformime segfault i strtok()

### ISSUE THREAD

**Issue by men2** [svarshavchik/courier-libs#8]
reformime -x crash with segmentation fault in the do_extract part of main2() if no mime sections are specified with the -s option. In this case reformime is supposed to extract all sections.
See gentoo bug with patch:
[https://bugs.gentoo.org/657288](https://bugs.gentoo.org/657288)

**Comment by svarshavchik** [comment]
This will be fixed in the next release. The portion of the patch that applies the same change to the -e option is unnecessary, because the man page documents that -s is required with that option, and an error message will be reported if it's missing.
