### ISSUE TITLE
waitlib/configure.ac on Alpine Linux does not check if wait3 working or not before giving up

### ISSUE THREAD

**Issue by githubat** [svarshavchik/courier-libs#9]
OS: Alpine Linux 3.8

Problem: configure script did not check if wait3 works or not (it does) on Alpine Linux before giving up, as it seems that the configure.ac script is at fault here, instead of the underlining Alpine Linux.

Suspected bug:

waitlib/configure.ac - line 64 - current is:

	if test "$has_sighold" = "yes"

Propose changed to:

	if test "$ac_cv_func_sighold" = "yes"

just like line 62 when checking sigblock as:

	if test "$ac_cv_func_sigblock" = "yes"

#####

Partial configure output from Alpine Linux 3.8:

checking for pid_t... yes
checking return type of signal handlers... void
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for wait... yes
checking for wait3... yes
checking for sigblock... no
checking for sighold... yes
checking for sigprocmask... yes
checking if wait function is broken... yes
configure: error: I give up -- neither wait nor wait3 works properly
configure: error: ./configure failed for libs/waitlib

#####

Bottom line, Alpine 3.8 does NOT have sigblock, but does have sighold

In current configure script, it seem the assumption is made that the "sigblock" will be defined, so the variable $has_xsig will be "yes" - which will trigger the configure script to check for wait3 system call if "wait" function call check failed.

However, on Alpine, sigblock is not defined, so $has_xsig equals to initial value of "no".

On line 64, the current checking of shell variable $has_sighold is never defined anywhere else in the configure script - so - right now line 64 does nothing - which makes configure.ac script declares that both wait and wait3 does not work on Alpine Linux - but actually never check wait3 working or not at all.

After either changed the line 64 to:

            if test "$ac_cv_func_sighold" = "yes"

OR 

use --with-waitfunc=wait3 with the top level configure script

then the configure process will finish without any errors on Alpine Linux, but does have compilation error.

Just my 2 cents input, hope it helps - THX!

**Comment by svarshavchik** [comment]
Fix commited, this should be fixed in the next release.
